package project

import (
	"os"
	"path/filepath"
	"strings"
)

// LocalStoragePubspecDeps returns the two pubspec.yaml dependency lines
// required by the generated LocalStorageService.
func LocalStoragePubspecDeps() string {
	return "  sqflite: ^2.3.3\n  path: ^1.9.0"
}

// GenerateLocalStorage writes lib/core/services/local_storage_service.dart
// into the Flutter project at projectPath.
//
// The generated service is a singleton that wraps SQLite via the sqflite
// package. It stores arbitrary Dart values as JSON TEXT in a key-value table,
// making it a drop-in local persistence layer that needs no schema design for
// rapid feature development.
func GenerateLocalStorage(projectPath string) error {
	servicesDir := filepath.Join(projectPath, "lib", "core", "services")
	if err := os.MkdirAll(servicesDir, 0755); err != nil {
		return err
	}
	return writeFile(
		filepath.Join(servicesDir, "local_storage_service.dart"),
		buildLocalStorageDart(),
	)
}

// buildLocalStorageDart returns the complete Dart source for LocalStorageService.
// The content is assembled via strings.Builder to avoid any Go string-literal
// delimiter conflicts with the Dart source (backticks, null-aware operators, etc.).
func buildLocalStorageDart() string {
	var b strings.Builder

	b.WriteString("import 'dart:convert';\n")
	b.WriteString("\n")
	b.WriteString("import 'package:path/path.dart' as p;\n")
	b.WriteString("import 'package:sqflite/sqflite.dart';\n")
	b.WriteString("\n")
	b.WriteString("/// A lightweight, JSON-based local key-value store backed by SQLite.\n")
	b.WriteString("///\n")
	b.WriteString("/// Usage\n")
	b.WriteString("/// -----\n")
	b.WriteString("/// Persist any JSON-serialisable value:\n")
	b.WriteString("///   await LocalStorageService.instance.save('user', {'id': 1, 'name': 'Ada'});\n")
	b.WriteString("///\n")
	b.WriteString("/// Retrieve it later (cast to the expected type):\n")
	b.WriteString("///   final user = await LocalStorageService.instance.get<Map<String, dynamic>>('user');\n")
	b.WriteString("///\n")
	b.WriteString("/// Delete a single entry:\n")
	b.WriteString("///   await LocalStorageService.instance.delete('user');\n")
	b.WriteString("///\n")
	b.WriteString("/// Wipe everything:\n")
	b.WriteString("///   await LocalStorageService.instance.clear();\n")
	b.WriteString("class LocalStorageService {\n")
	b.WriteString("  LocalStorageService._internal();\n")
	b.WriteString("\n")
	b.WriteString("  static final LocalStorageService instance = LocalStorageService._internal();\n")
	b.WriteString("\n")
	b.WriteString("  Database? _db;\n")
	b.WriteString("\n")
	b.WriteString("  // -- Initialisation ----------------------------------------------------------\n")
	b.WriteString("\n")
	b.WriteString("  Future<Database> get _database async {\n")
	b.WriteString("    _db ??= await _openDatabase();\n")
	b.WriteString("    return _db!;\n")
	b.WriteString("  }\n")
	b.WriteString("\n")
	b.WriteString("  Future<Database> _openDatabase() async {\n")
	b.WriteString("    final dbPath = await getDatabasesPath();\n")
	b.WriteString("    final path = p.join(dbPath, 'local_storage.db');\n")
	b.WriteString("\n")
	b.WriteString("    return openDatabase(\n")
	b.WriteString("      path,\n")
	b.WriteString("      version: 1,\n")
	b.WriteString("      onCreate: (db, version) async {\n")
	b.WriteString("        await db.execute('''\n")
	b.WriteString("          CREATE TABLE IF NOT EXISTS storage (\n")
	b.WriteString("            id          INTEGER PRIMARY KEY AUTOINCREMENT,\n")
	b.WriteString("            key         TEXT    NOT NULL UNIQUE,\n")
	b.WriteString("            value       TEXT    NOT NULL,\n")
	b.WriteString("            created_at  TEXT    NOT NULL,\n")
	b.WriteString("            updated_at  TEXT    NOT NULL\n")
	b.WriteString("          )\n")
	b.WriteString("        ''');\n")
	b.WriteString("      },\n")
	b.WriteString("    );\n")
	b.WriteString("  }\n")
	b.WriteString("\n")
	b.WriteString("  // -- Write -------------------------------------------------------------------\n")
	b.WriteString("\n")
	b.WriteString("  /// Persists [value] under [key].\n")
	b.WriteString("  ///\n")
	b.WriteString("  /// [value] must be JSON-serialisable (Map, List, String, num, bool, null).\n")
	b.WriteString("  /// Calling save() with an existing [key] overwrites the previous value.\n")
	b.WriteString("  Future<void> save(String key, dynamic value) async {\n")
	b.WriteString("    final db  = await _database;\n")
	b.WriteString("    final now = DateTime.now().toIso8601String();\n")
	b.WriteString("\n")
	b.WriteString("    await db.insert(\n")
	b.WriteString("      'storage',\n")
	b.WriteString("      {\n")
	b.WriteString("        'key':        key,\n")
	b.WriteString("        'value':      jsonEncode(value),\n")
	b.WriteString("        'created_at': now,\n")
	b.WriteString("        'updated_at': now,\n")
	b.WriteString("      },\n")
	b.WriteString("      conflictAlgorithm: ConflictAlgorithm.replace,\n")
	b.WriteString("    );\n")
	b.WriteString("  }\n")
	b.WriteString("\n")
	b.WriteString("  // -- Read --------------------------------------------------------------------\n")
	b.WriteString("\n")
	b.WriteString("  /// Returns the value stored under [key], decoded as [T].\n")
	b.WriteString("  ///\n")
	b.WriteString("  /// Returns null when the key does not exist.\n")
	b.WriteString("  Future<T?> get<T>(String key) async {\n")
	b.WriteString("    final db   = await _database;\n")
	b.WriteString("    final rows = await db.query(\n")
	b.WriteString("      'storage',\n")
	b.WriteString("      columns:   ['value'],\n")
	b.WriteString("      where:     'key = ?',\n")
	b.WriteString("      whereArgs: [key],\n")
	b.WriteString("      limit:     1,\n")
	b.WriteString("    );\n")
	b.WriteString("\n")
	b.WriteString("    if (rows.isEmpty) return null;\n")
	b.WriteString("\n")
	b.WriteString("    final decoded = jsonDecode(rows.first['value'] as String);\n")
	b.WriteString("    if (decoded is T) return decoded;\n")
	b.WriteString("    return null;\n")
	b.WriteString("  }\n")
	b.WriteString("\n")
	b.WriteString("  /// Returns every stored entry as a Map<String, dynamic> where each\n")
	b.WriteString("  /// value has already been JSON-decoded.\n")
	b.WriteString("  Future<Map<String, dynamic>> getAll() async {\n")
	b.WriteString("    final db   = await _database;\n")
	b.WriteString("    final rows = await db.query('storage');\n")
	b.WriteString("\n")
	b.WriteString("    return {\n")
	b.WriteString("      for (final row in rows)\n")
	b.WriteString("        row['key'] as String: jsonDecode(row['value'] as String),\n")
	b.WriteString("    };\n")
	b.WriteString("  }\n")
	b.WriteString("\n")
	b.WriteString("  /// Returns true when a value exists for [key].\n")
	b.WriteString("  Future<bool> containsKey(String key) async {\n")
	b.WriteString("    final db   = await _database;\n")
	b.WriteString("    final rows = await db.query(\n")
	b.WriteString("      'storage',\n")
	b.WriteString("      columns:   ['id'],\n")
	b.WriteString("      where:     'key = ?',\n")
	b.WriteString("      whereArgs: [key],\n")
	b.WriteString("      limit:     1,\n")
	b.WriteString("    );\n")
	b.WriteString("    return rows.isNotEmpty;\n")
	b.WriteString("  }\n")
	b.WriteString("\n")
	b.WriteString("  /// Returns every stored key in insertion order.\n")
	b.WriteString("  Future<List<String>> getKeys() async {\n")
	b.WriteString("    final db   = await _database;\n")
	b.WriteString("    final rows = await db.query('storage', columns: ['key']);\n")
	b.WriteString("    return rows.map((r) => r['key'] as String).toList();\n")
	b.WriteString("  }\n")
	b.WriteString("\n")
	b.WriteString("  // -- Delete ------------------------------------------------------------------\n")
	b.WriteString("\n")
	b.WriteString("  /// Removes the entry for [key]. No-op if the key does not exist.\n")
	b.WriteString("  Future<void> delete(String key) async {\n")
	b.WriteString("    final db = await _database;\n")
	b.WriteString("    await db.delete('storage', where: 'key = ?', whereArgs: [key]);\n")
	b.WriteString("  }\n")
	b.WriteString("\n")
	b.WriteString("  /// Deletes every entry in the store.\n")
	b.WriteString("  Future<void> clear() async {\n")
	b.WriteString("    final db = await _database;\n")
	b.WriteString("    await db.delete('storage');\n")
	b.WriteString("  }\n")
	b.WriteString("\n")
	b.WriteString("  // -- Lifecycle ---------------------------------------------------------------\n")
	b.WriteString("\n")
	b.WriteString("  /// Closes the underlying database connection.\n")
	b.WriteString("  ///\n")
	b.WriteString("  /// The service will re-open the database automatically on the next\n")
	b.WriteString("  /// read/write call, so manual close() is only needed during testing or\n")
	b.WriteString("  /// when the app is shutting down cleanly.\n")
	b.WriteString("  Future<void> close() async {\n")
	b.WriteString("    await _db?.close();\n")
	b.WriteString("    _db = null;\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}
